---
title: "Single Cell LY49"
author: "Malassigne_Victor"
date: "11/15/2022"
output: 
  html_document:
    toc: yes
    toc_depth: 3
---

# 1 Library  
```{r, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = T, fig.height=9, fig.width=9, fig.align="center")

if (!require('Seurat')) install.packages('Seurat'); library('Seurat')
if (!require('dplyr')) install.packages('dplyr'); library('dplyr')
if (!require('khroma')) install.packages('khroma'); library('khroma')
if (!require('future')) install.packages('future'); library('future')
if (!require('clustree')) install.packages('clustree'); library('clustree')
if (!require('ggplot2')) install.packages('ggplot2'); library('ggplot2')
if (!require('openxlsx')) install.packages('openxlsx'); library('openxlsx')
if (!require('tidyr')) install.packages('tidyr'); library('tidyr')
if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
if (!require('org.Mm.eg.db')) BiocManager::install('org.Mm.eg.db'); library('org.Mm.eg.db')
if (!require('AnnotationDbi')) BiocManager::install('AnnotationDbi'); library('AnnotationDbi')
if (!require('enrichplot')) BiocManager::install('enrichplot'); library('enrichplot')
if (!require('clusterProfiler')) BiocManager::install('clusterProfiler'); library('clusterProfiler')
if (!require('ReactomePA')) BiocManager::install('ReactomePA'); library('ReactomePA')
if (!require('AUCell')) BiocManager::install('AUCell'); library('AUCell')
```

# 2 import data  
```{r, echo=FALSE, message=FALSE, warning=FALSE}
rm(list = ls())
plan("multiprocess", workers = 9) # activate parallelization

Singlet_norm <- readRDS("~/Documents/JM/singelcell_LY49/data/Singlet_norm_3.RDS")
Singlet_norm.markers_befor <- read.xlsx("~/Documents/JM/singelcell_LY49/SC_Ly49_10X/results/DE_befor_clusterization.xlsx")
Singlet_norm.markers_after <- read.xlsx("~/Documents/JM/singelcell_LY49/SC_Ly49_10X/results/DE_after_clusterization_reso04.xlsx")
Singlet_norm.markers_after_05 <- read.xlsx("~/Documents/JM/singelcell_LY49/SC_Ly49_10X/results/DE_after_clusterization_reso05.xlsx")

my_palette = c("Naive"= "#AA4499",
               "Ly49n"= "#332288",
               "VV-B8R"= "#DDCC77",
               "Ly49p-CD8ab"= "#117733",
               "Ly49p-CD8aa"= "#88CCEE",
               "VV-Ly49p-CD8ab"= "#999933",
               "VV-Ly49p-CD8aa"= "#882255",
               "G1" = "salmon2",
               "G2M" = "green4",
               "S" = "dodgerblue")
```
  
DE avec une résolition de 0.5, 11 clusters et 1976 gènes.  
DE avec une résolition de 0.4, 9 clusters et 1448 gènes.  

# 3 PCA UMAP cluster DE
```{r, echo=FALSE, message=FALSE, warning=FALSE}
### PCA ####
DimPlot(Singlet_norm,
        reduction = "pca",
        group.by = "HTO_maxID",
        pt.size = 1,
        cols = my_palette)+
  labs(color = "legend ")+
  ggtitle(label = "PCA")

### UMAP ###
DimPlot(Singlet_norm,
        reduction = "umap",
        group.by = "HTO_maxID",
        pt.size = 1,
        cols = my_palette,
        label = T) +
  labs(color = "Legend :") +
  ggtitle(label = paste0("UMAP 11 CP"))

### UMAP cluster ###
DimPlot(Singlet_norm,
        reduction = "umap",
        group.by = "SCT_snn_res.0.4",
        pt.size = 1,
        label = T)+
  labs(color = "legend ")+
  ggtitle(label = paste0( "UMAP 11 CP et resolution : 0.4"))

### UMAP with Gzmm ###
FeaturePlot(Singlet_norm, features = "Gzmm")
### UMAP with Klrb1c ###
FeaturePlot(Singlet_norm, features = "Klrb1c")

FeaturePlot(Singlet_norm, features = "Tcrg-C1")
FeaturePlot(Singlet_norm, features = "Tcrg-C2")
FeaturePlot(Singlet_norm, features = "Tcrg-C3")
FeaturePlot(Singlet_norm, features = "Tcrg-V1")
FeaturePlot(Singlet_norm, features = "Tcrg-V3")
FeaturePlot(Singlet_norm, features = "Tcrg-V4")
FeaturePlot(Singlet_norm, features = "Tcrg-V6")

FeaturePlot(Singlet_norm, features = "Fcgrt")
FeaturePlot(Singlet_norm, features = "Fcer1g")

FeaturePlot(Singlet_norm, features = "Cxcr5")
FeaturePlot(Singlet_norm, features = "Klrd1")
FeaturePlot(Singlet_norm, features = "Klrc1")
FeaturePlot(Singlet_norm, features = "H2-Q2")
FeaturePlot(Singlet_norm, features = "H2-Q4")
FeaturePlot(Singlet_norm, features = "H2-Q6")
FeaturePlot(Singlet_norm, features = "H2-Q7")
FeaturePlot(Singlet_norm, features = "H2-Q10")
FeaturePlot(Singlet_norm, features = "H2-T23")
FeaturePlot(Singlet_norm, features = "H2-Aa")
FeaturePlot(Singlet_norm, features = "H2-Ab1")
FeaturePlot(Singlet_norm, features = "Tcf7")

	

FeaturePlot(Singlet_norm, features = "Fcgr2b")
FeaturePlot(Singlet_norm, features = "Fcgr3")
FeaturePlot(Singlet_norm, features = "Fcgrt")
FeaturePlot(Singlet_norm, features = "Fcer1g")
FeaturePlot(Singlet_norm, features = "Cxcr5")

FeaturePlot(Singlet_norm, features = "Lnpep")
FeaturePlot(Singlet_norm, features = "Syk")
FeaturePlot(Singlet_norm, features = "Zap70")


### DE ###
###### Population ######
Singlet_norm.markers_befor %>%
  group_by(cluster) %>%
  top_n(n = 10, wt = avg_log2FC) -> top10

DoHeatmap(Singlet_norm, features = top10$gene, group.by = "HTO_maxID", group.colors = my_palette) +
  # NoLegend() +
  ggtitle(label = "Heatmaps du DE top 10 gènes entre les différentes populations")

###### Cluster ######
Singlet_norm.markers_after %>%
  group_by(cluster) %>%
  top_n(n = 10, wt = avg_log2FC) -> top10

DoHeatmap(Singlet_norm, features = top10$gene, group.by = "SCT_snn_res.0.4") +
  # NoLegend() +
  ggtitle(label = "Heatmaps du DE top 10 gènes entre les différents clusters")
```



# DE all
```{r, echo=FALSE, message=FALSE, warning=FALSE}
namepop <- c("VV-B8R", "Ly49p-CD8ab", "VV-Ly49p-CD8aa", "Ly49p-CD8aa", "VV-Ly49p-CD8ab", "Naive", "Ly49n")
nameclus <- c("0", "1", "2", "3", "4", "5", "6", "7", "8")

### population ###
counter = 0
for (i in namepop) {
  counter = counter + 1
  for (j in namepop[counter  : 7]) {
    print(paste0("DE ", i, " vs ", j))
    c <- FindMarkers(Singlet_norm,
                                    group.by = "HTO_maxID",
                                    ident.1 = i,
                                    ident.2 = j,
                                    only.pos = F,
                                    min.pct = 0.1, #  diff de 0.1 entre les deux conditions
                                    logfc.threshold = 0.5,
                                    min.diff.pct = 0.25)
    if (length(t(c)) > 0) {
      print(c %>%
        arrange(-avg_log2FC) %>%
        top_n(n = 30, wt = avg_log2FC) )
      plot <- DoHeatmap(Singlet_norm, features = rownames(c[0:30,]), group.by = "HTO_maxID", group.colors = my_palette) +
      # NoLegend() +
      ggtitle(label = paste0("Heatmaps du DE ", i, " vs ", j))
      print(plot)
    }

  }

}

### cluster ###
counter = 0
for (i in nameclus) {
  counter = counter + 1
  for (j in nameclus[counter  : 9]) {
    print(paste0("DE ", i, " vs ", j))
    c <- FindMarkers(Singlet_norm,
                                    group.by = "SCT_snn_res.0.4",
                                    ident.1 = i,
                                    ident.2 = j,
                                    only.pos = F,
                                    min.pct = 0.1, #  diff de 0.1 entre les deux conditions
                                    logfc.threshold = 0.5,
                                    min.diff.pct = 0.25)
    if (length(t(c)) > 0) {
      print(c %>%
        arrange(-avg_log2FC) %>%
        top_n(n = 30, wt = avg_log2FC) )
      plot <- DoHeatmap(Singlet_norm, features = rownames(c[0:30,]), group.by = "SCT_snn_res.0.4") +
      # NoLegend() +
      ggtitle(label = paste0("Heatmaps du DE ", i, " vs ", j))
      print(plot)
    }

  }

}


# ####### TEST volcanoplot ###############
# RESgg <- c %>%
#   mutate(p_val_col = case_when(p_val >= 0.05 ~ "ns",
#                                avg_log2FC > 0 ~ "up",
#                                avg_log2FC < 0 ~ "down")) %>%
#   ggplot(aes(x = avg_log2FC, y = -log10(p_val),
#              color = p_val_col)) +
#   geom_point() +
#   scale_color_manual(values = c("gray", "indianred", "palegreen3"),
#                      limits = c("ns", "up", "down")) +
#   geom_hline(yintercept = -log10(0.05),
#              linetype = "dashed") +
#   theme_bw() +
#   theme(legend.position = "none")
# RESgg
```

# 5 Classify cells as G2/M, S, or alternatively G1
```{r, echo=FALSE, message=FALSE, warning=FALSE}
# A list of cell cycle markers, from Tirosh et al, 2015, is loaded with Seurat.  We can
# segregate this list into markers of G2/M phase and markers of S phase
s.genes <- cc.genes$s.genes
s.genes <- tolower(s.genes)
firstup <- function(x) {
  substr(x, 1, 1) <- toupper(substr(x, 1, 1))
  x
}
s.genes <- firstup(s.genes)
g2m.genes <- cc.genes$g2m.genes
g2m.genes <- tolower(g2m.genes)
g2m.genes <- firstup(g2m.genes)


Singlet_norm <- CellCycleScoring(Singlet_norm,
                               s.features = s.genes,
                               g2m.features = g2m.genes,
                               set.ident = TRUE)
```

## 5.1 Visualization
```{r, echo=FALSE, message=FALSE, warning=FALSE}
DimPlot(Singlet_norm,
        reduction = "umap",
        group.by = "Phase",
        pt.size = 1,
        cols = my_palette) +
  ggtitle(label = "Cell Cycle Phase")

# Visualize the distribution of cell cycle markers across
RidgePlot(Singlet_norm, features = c("Pcna", "Top2a", "Mcm6", "Mki67"), ncol = 2, cols = my_palette)
```

# 6 Creat metadata
```{r, echo=FALSE, message=FALSE, warning=FALSE}
metadata <- as.data.frame(Singlet_norm@meta.data[["HTO_maxID"]])
metadata <- cbind(metadata,as.data.frame(Singlet_norm@meta.data[["Phase"]]))
metadata <- cbind(metadata, as.data.frame(Singlet_norm@meta.data[["SCT_snn_res.0.4"]]))
colnames(metadata)<- c("population","phase","cluster")
```

## 6.1 Visualization Cell cycle phase by cluster
```{r, echo=FALSE, message=FALSE, warning=FALSE}
metadata %>%
  count(cluster, phase) %>%
  arrange(cluster, phase) %>%
  mutate(pct_total = n / sum(n) * 100) -> a

clus <- seq(0,10,1)
Metadata_final <- NULL
for (i in clus) {
  inter <- a[which(a$cluster %in% i),]
  inter <- inter %>%
    mutate(pct_cluster = n / sum(n) * 100)
  Metadata_final <- rbind(Metadata_final, inter)
}

### percent ###
ggplot(Metadata_final, aes(fill = phase, y = pct_cluster, x = cluster)) +
  geom_bar(position='dodge', stat='identity') +
  scale_fill_manual(values= my_palette) +
  theme_minimal() +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  ggtitle(label = "Cell cycle phase by cluster")

ggplot(Metadata_final, aes(fill=phase, y=pct_cluster, x=phase)) +
  geom_bar(position='dodge', stat='identity') +
  scale_fill_manual(values= my_palette) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1.05, hjust=1),
        panel.background = element_blank(),
        axis.line = element_line(colour = "grey")) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  ggtitle(label = paste0("Cell cycle phase by cluster in percent")) +
  facet_wrap(~cluster, scales='free_x')

### absolute ###
ggplot(Metadata_final, aes(fill = phase, y = n, x = cluster)) +
  geom_bar(position='dodge', stat='identity') +
  scale_fill_manual(values= my_palette) +
  theme_minimal() +
  scale_y_continuous(limits = c(0,1500)) +
  ggtitle(label = "Cell cycle phase by cluster")

ggplot(Metadata_final, aes(fill=phase, y=n, x=phase)) +
  geom_bar(position='dodge', stat='identity') +
  scale_fill_manual(values= my_palette) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1.05, hjust=1),
        panel.background = element_blank(),
        axis.line = element_line(colour = "grey")) +
  scale_y_continuous(limits = c(0,1500)) +
  ggtitle(label = paste0("Cell cycle phase by cluster ")) +
  facet_wrap(~cluster, scales='free_x')
```

## 6.2 Visualization population by cluster
```{r, echo=FALSE, message=FALSE, warning=FALSE}
metadata %>%
  count(population, cluster) %>%
  arrange(cluster, population) %>%
  mutate(pct_total = n / sum(n) * 100) -> a

clus <- seq(0,10,1)
Metadata_final <- NULL
for (i in clus) {
  inter <- a[which(a$cluster %in% i),]
  inter <- inter %>%
    mutate(pct_cluster = n / sum(n) * 100)
  Metadata_final <- rbind(Metadata_final, inter)
}

### percent ###
ggplot(Metadata_final, aes(fill=population, y=pct_cluster, x=cluster)) +
  geom_bar(position='dodge', stat='identity') +
  scale_fill_manual(values= my_palette) +
  theme_minimal() +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  ggtitle(label = "Population by cluster")

ggplot(Metadata_final, aes(fill=population, y=pct_cluster, x=population)) +
  geom_bar(position='dodge', stat='identity') +
  theme(axis.text.x = element_text(angle = 45, vjust = 1.05, hjust=1),
        panel.background = element_blank(),
        axis.line = element_line(colour = "grey")) +
  scale_fill_manual(values= my_palette) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  ggtitle(label = paste0("Population by cluster in percent")) +
  facet_wrap(~cluster, scales='free_x')

### Absolute ###
ggplot(Metadata_final, aes(fill=population, y=n, x=cluster)) +
  geom_bar(position='dodge', stat='identity') +
  scale_fill_manual(values= my_palette) +
  theme_minimal() +
  scale_y_continuous(limits = c(0,1200)) +
  ggtitle(label = "Population by cluster")

ggplot(Metadata_final, aes(fill=population, y=n, x=population)) +
  geom_bar(position='dodge', stat='identity') +
  theme(axis.text.x = element_text(angle = 45, vjust = 1.05, hjust=1),
        panel.background = element_blank(),
        axis.line = element_line(colour = "grey")) +
  scale_fill_manual(values= my_palette) +
  scale_y_continuous(limits = c(0,1200)) +
  ggtitle(label = paste0("Population by cluster")) +
  facet_wrap(~cluster, scales='free_x')
```

<!-- # 7 Enrichment -->
<!-- ## 7.1 Enrichment with single DE genes per cluster -->
<!-- ```{r, echo=FALSE, message=FALSE, warning=FALSE} -->
<!-- clus <- seq(0,6,1) -->
<!-- # par(mfrow = c(2,2)) -->
<!-- for (i in clus) { -->
<!--   inter <- Singlet_norm.markers_after[which(Singlet_norm.markers_after$cluster %in% i),] -->
<!--   # print(unique(inter)) -->

<!--   # KEGG ------------------------------------------------------------------------- -->
<!--   geneListEntrez = mapIds(org.Mm.eg.db, -->
<!--                           keys=inter$gene, -->
<!--                           column="ENTREZID", -->
<!--                           keytype="SYMBOL", -->
<!--                           multiVals="first") -->

<!--   Kres <- enrichKEGG(gene         = geneListEntrez, -->
<!--                      organism     = "mmu", -->
<!--                     pAdjustMethod = "BH", -->
<!--                     minGSSize    = 3, -->
<!--                     pvalueCutoff  = 0.05, # slider -->
<!--                     qvalueCutoff  = 0.05) # slider -->

<!--   # Kresmat = as.matrix(Kres[]) -->

<!--   plot5 <- barplot(Kres, showCategory=15, order=T) + ggtitle(paste0("Barplot of functional enrichment by KEGG for cluster ", i)) -->
<!--   plot6 <- dotplot(Kres, showCategory=15) + ggtitle(paste0("Dotplot of functional enrichment by KEGG for cluster ", i)) -->

<!--   # GO --------------------------------------------------------------------------- -->
<!--   geneListEnsembl= mapIds(org.Mm.eg.db, -->
<!--                           keys=inter$gene, -->
<!--                           column="ENSEMBL", -->
<!--                           keytype="SYMBOL", -->
<!--                           multiVals="first") -->

<!--   enrichedRes_GO  <- enrichGO( -->
<!--     gene          = geneListEnsembl, -->
<!--     keyType       = "ENSEMBL", -->
<!--     OrgDb         = org.Mm.eg.db, -->
<!--     ont           = "BP", -->
<!--     pAdjustMethod = "BH", -->
<!--     minGSSize    = 3, -->
<!--     pvalueCutoff  = 0.05, # slider -->
<!--     qvalueCutoff  = 0.05,# slider -->
<!--     readable      = TRUE) -->

<!--   # enrichedRes_GO_mat = as.matrix(enrichedRes_GO[]) -->

<!--   plot1 <- barplot(enrichedRes_GO, showCategory=15, order=T) + ggtitle(paste0("Barplot of functional enrichment by GO for cluster ", i)) -->
<!--   plot2 <- dotplot(enrichedRes_GO, showCategory=15) + ggtitle(paste0("Dotplot of functional enrichment by GO for cluster ", i)) -->

<!--   # REACTOM_PA-------------------------------------------------------------------- -->
<!--   geneListEntrez_PA = mapIds(org.Mm.eg.db, -->
<!--                              keys=inter$gene, -->
<!--                              column="ENTREZID", -->
<!--                              keytype="SYMBOL", -->
<!--                              multiVals="first") -->

<!--   enrichedRes_GS <- enrichPathway(gene = geneListEntrez_PA, -->
<!--                                   organism = 'mouse', -->
<!--                                   pAdjustMethod = "BH", -->
<!--                                   minGSSize    = 3, -->
<!--                                   pvalueCutoff  = 0.05, # slider -->
<!--                                   qvalueCutoff  = 0.05) -->

<!--   # enrichedRes_GS_mat = as.matrix(enrichedRes_GS[]) -->

<!--   plot3 <- barplot(enrichedRes_GS, showCategory=15, orderby="x") + ggtitle(paste0("Barplot of functional enrichment by REACTOM_PA for cluster", i)) -->
<!--   plot4 <- dotplot(enrichedRes_GS, showCategory=15) + ggtitle(paste0("Dotplot of functional enrichment by REACTOM_PA for cluster", i)) -->

<!--   # print(plot5) -->
<!--   print(plot6) -->
<!--   # print(plot1) -->
<!--   print(plot2) -->
<!--   # print(plot3) -->
<!--   print(plot4) -->
<!-- } -->

<!-- clus <- 7 -->
<!-- for (i in clus) { -->
<!--   print(i) -->
<!--   inter <- Singlet_norm.markers_after[which(Singlet_norm.markers_after$cluster %in% i),] -->
<!--   # print(unique(inter)) -->

<!--   # KEGG ------------------------------------------------------------------------- -->
<!--   geneListEntrez = mapIds(org.Mm.eg.db, -->
<!--                           keys=inter$gene, -->
<!--                           column="ENTREZID", -->
<!--                           keytype="SYMBOL", -->
<!--                           multiVals="first") -->

<!--   Kres <- enrichKEGG(gene         = geneListEntrez, -->
<!--                      organism     = "mmu", -->
<!--                      pAdjustMethod = "BH", -->
<!--                      minGSSize    = 3, -->
<!--                                   pvalueCutoff  = 0.05, # slider -->
<!--                                   qvalueCutoff  = 0.05) -->

<!--   # Kresmat = as.matrix(Kres[]) -->

<!--   plot5 <- barplot(Kres, showCategory=15, order=T) + ggtitle(paste0("Barplot of functional enrichment by KEGG for cluster ", i)) -->
<!--   plot6 <- dotplot(Kres, showCategory=15) + ggtitle(paste0("Dotplot of functional enrichment by KEGG for cluster ", i)) -->

<!--   # GO --------------------------------------------------------------------------- -->
<!--   geneListEnsembl= mapIds(org.Mm.eg.db, -->
<!--                           keys=inter$gene, -->
<!--                           column="ENSEMBL", -->
<!--                           keytype="SYMBOL", -->
<!--                           multiVals="first") -->

<!--   enrichedRes_GO  <- enrichGO( -->
<!--     gene          = geneListEnsembl, -->
<!--     keyType       = "ENSEMBL", -->
<!--     OrgDb         = org.Mm.eg.db, -->
<!--     ont = "BP", -->
<!--                                   pAdjustMethod = "BH", -->
<!--                                   minGSSize    = 3, -->
<!--                                   pvalueCutoff  = 0.05, # slider -->
<!--                                   qvalueCutoff  = 0.05, -->
<!--     readable      = TRUE) -->

<!--   # enrichedRes_GO_mat = as.matrix(enrichedRes_GO[]) -->

<!--   plot1 <- barplot(enrichedRes_GO, showCategory=15, order=T) + ggtitle(paste0("Barplot of functional enrichment by GO for cluster ", i)) -->
<!--   plot2 <- dotplot(enrichedRes_GO, showCategory=15) + ggtitle(paste0("Dotplot of functional enrichment by GO for cluster ", i)) -->

<!--   # print(plot5) -->
<!--   print(plot6) -->
<!--   # print(plot1) -->
<!--   print(plot2) -->
<!-- } -->

<!-- clus <- seq(8,10,1) -->
<!-- # par(mfrow = c(2,2)) -->
<!-- for (i in clus) { -->
<!--   print(i) -->
<!--   inter <- Singlet_norm.markers_after[which(Singlet_norm.markers_after$cluster %in% i),] -->
<!--   # print(unique(inter)) -->

<!--   # KEGG ------------------------------------------------------------------------- -->
<!--   geneListEntrez = mapIds(org.Mm.eg.db, -->
<!--                           keys=inter$gene, -->
<!--                           column="ENTREZID", -->
<!--                           keytype="SYMBOL", -->
<!--                           multiVals="first") -->

<!--   Kres <- enrichKEGG(gene         = geneListEntrez, -->
<!--                      organism     = "mmu", -->
<!--                                   pAdjustMethod = "BH", -->
<!--                                   minGSSize    = 3, -->
<!--                                   pvalueCutoff  = 0.05, # slider -->
<!--                                   qvalueCutoff  = 0.05) -->

<!--   # Kresmat = as.matrix(Kres[]) -->

<!--   plot5 <- barplot(Kres, showCategory=15, order=T) + ggtitle(paste0("Barplot of functional enrichment by KEGG for cluster ", i)) -->
<!--   plot6 <- dotplot(Kres, showCategory=15) + ggtitle(paste0("Dotplot of functional enrichment by KEGG for cluster ", i)) -->

<!--   # GO --------------------------------------------------------------------------- -->
<!--   geneListEnsembl= mapIds(org.Mm.eg.db, -->
<!--                           keys=inter$gene, -->
<!--                           column="ENSEMBL", -->
<!--                           keytype="SYMBOL", -->
<!--                           multiVals="first") -->

<!--   enrichedRes_GO  <- enrichGO( -->
<!--     gene          = geneListEnsembl, -->
<!--     keyType       = "ENSEMBL", -->
<!--     OrgDb         = org.Mm.eg.db, -->
<!--     ont           = "BP", -->
<!--                                   pAdjustMethod = "BH", -->
<!--                                   minGSSize    = 3, -->
<!--                                   pvalueCutoff  = 0.05, # slider -->
<!--                                   qvalueCutoff  = 0.05, -->
<!--     readable      = TRUE) -->

<!--   # enrichedRes_GO_mat = as.matrix(enrichedRes_GO[]) -->

<!--   plot1 <- barplot(enrichedRes_GO, showCategory=15, order=T) + ggtitle(paste0("Barplot of functional enrichment by GO for cluster ", i)) -->
<!--   plot2 <- dotplot(enrichedRes_GO, showCategory=15) + ggtitle(paste0("Dotplot of functional enrichment by GO for cluster ", i)) -->

<!--   # REACTOM_PA-------------------------------------------------------------------- -->
<!--   geneListEntrez_PA = mapIds(org.Mm.eg.db, -->
<!--                              keys=inter$gene, -->
<!--                              column="ENTREZID", -->
<!--                              keytype="SYMBOL", -->
<!--                              multiVals="first") -->

<!--   enrichedRes_GS <- enrichPathway(gene = geneListEntrez_PA, -->
<!--                                   organism = 'mouse', -->
<!--                                   pAdjustMethod = "BH", -->
<!--                                   minGSSize    = 3, -->
<!--                                   pvalueCutoff  = 0.05, # slider -->
<!--                                   qvalueCutoff  = 0.05) -->

<!--   # enrichedRes_GS_mat = as.matrix(enrichedRes_GS[]) -->

<!--   plot3 <- barplot(enrichedRes_GS, showCategory=15, orderby="x") + ggtitle(paste0("Barplot of functional enrichment by REACTOM_PA for cluster", i)) -->
<!--   plot4 <- dotplot(enrichedRes_GS, showCategory=15) + ggtitle(paste0("Dotplot of functional enrichment by REACTOM_PA for cluster", i)) -->

<!--   # print(plot5) -->
<!--   print(plot6) -->
<!--   # print(plot1) -->
<!--   print(plot2) -->
<!--   # print(plot3) -->
<!--   print(plot4) -->
<!-- } -->
<!-- ``` -->

<!-- ## 7.2 Enrichment with gene DE population vs population -->
<!-- ```{r, echo=FALSE, message=FALSE, warning=FALSE} -->
<!-- pop <- list(DE_LY49p_CD8aa_vs_ab,DE_LY49p_CD8aa_vs_VV_aa,DE_LY49p_CD8ab_vs_VV_ab,DE_VV_LY49p_CD8aa_vs_ab) -->
<!-- namepop <- c("DE_LY49p_CD8aa_vs_ab","DE_LY49p_CD8aa_vs_VV_aa","DE_LY49p_CD8ab_vs_VV_ab","DE_VV_LY49p_CD8aa_vs_ab") -->
<!-- print(namepop) -->
<!-- for (i in pop) { -->
<!--     # KEGG ------------------------------------------------------------------------- -->
<!--     geneListEntrez = mapIds(org.Mm.eg.db, -->
<!--                             keys=rownames(i), -->
<!--                             column="ENTREZID", -->
<!--                             keytype="SYMBOL", -->
<!--                             multiVals="first") -->

<!--     Kres <- enrichKEGG(gene         = geneListEntrez, -->
<!--                        organism     = "mmu", -->
<!--                                                          pAdjustMethod = "BH", -->
<!--                                   minGSSize    = 3, -->
<!--                                   pvalueCutoff  = 0.05, # slider -->
<!--                                   qvalueCutoff  = 0.05) -->

<!--     # Kresmat = as.matrix(Kres[]) -->

<!--     plot5 <- barplot(Kres, showCategory=15, order=T) + ggtitle(paste0("Barplot of functional enrichment by KEGG for population ")) -->
<!--     plot6 <- dotplot(Kres, showCategory=15) + ggtitle(paste0("Dotplot of functional enrichment by KEGG for population ")) -->

<!--     # GO --------------------------------------------------------------------------- -->
<!--     geneListEnsembl= mapIds(org.Mm.eg.db, -->
<!--                             keys=rownames(i), -->
<!--                             column="ENSEMBL", -->
<!--                             keytype="SYMBOL", -->
<!--                             multiVals="first") -->

<!--     enrichedRes_GO  <- enrichGO( -->
<!--       gene          = geneListEnsembl, -->
<!--       keyType       = "ENSEMBL", -->
<!--       OrgDb         = org.Mm.eg.db, -->
<!--       ont           = "BP", -->
<!--                                   pAdjustMethod = "BH", -->
<!--                                   minGSSize    = 3, -->
<!--                                   pvalueCutoff  = 0.05, # slider -->
<!--                                   qvalueCutoff  = 0.05, -->
<!--       readable      = TRUE) -->

<!--     # enrichedRes_GO_mat = as.matrix(enrichedRes_GO[]) -->

<!--     plot1 <- barplot(enrichedRes_GO, showCategory=15, order=T) + ggtitle(paste0("Barplot of functional enrichment by GO for population ")) -->
<!--     plot2 <- dotplot(enrichedRes_GO, showCategory=15) + ggtitle(paste0("Dotplot of functional enrichment by GO for population ")) -->

<!--     # REACTOM_PA-------------------------------------------------------------------- -->
<!--     geneListEntrez_PA = mapIds(org.Mm.eg.db, -->
<!--                                keys=rownames(i), -->
<!--                                column="ENTREZID", -->
<!--                                keytype="SYMBOL", -->
<!--                                multiVals="first") -->

<!--     enrichedRes_GS <- enrichPathway(gene = geneListEntrez_PA, -->
<!--                                     organism = 'mouse', -->
<!--                                   pAdjustMethod = "BH", -->
<!--                                   minGSSize    = 3, -->
<!--                                   pvalueCutoff  = 0.05, # slider -->
<!--                                   qvalueCutoff  = 0.05) -->

<!--     enrichedRes_GS_mat = as.matrix(enrichedRes_GS[]) -->

<!--     plot3 <- barplot(enrichedRes_GS, showCategory=15, orderby="x") + ggtitle(paste0("Barplot of functional enrichment by REACTOM_PA for population")) -->
<!--     plot4 <- dotplot(enrichedRes_GS, showCategory=15) + ggtitle(paste0("Dotplot of functional enrichment by REACTOM_PA for population")) -->

<!--     # print(plot5) -->
<!--     print(plot6) -->
<!--     # print(plot1) -->
<!--     print(plot2) -->
<!--     # print(plot3) -->
<!--     print(plot4) -->
<!-- } -->
<!-- ``` -->

<!-- ## 7.3 Enrichment with gene DE cluster vs cluster -->
<!-- ```{r, echo=FALSE, message=FALSE, warning=FALSE} -->
<!-- clus <- list(DE_1_vs_2,DE_1_vs_4,DE_1_vs_2_4,DE_0_vs_1,DE_0_vs_2,DE_0_vs_4,DE_0_vs_1_2_4_7) -->
<!-- nameclus <- c("DE_1_vs_2","DE_1_vs_4","DE_1_vs_2_4","DE_0_vs_1","DE_0_vs_2","DE_0_vs_4","DE_0_vs_1_2_4_7") -->
<!-- print(nameclus) -->

<!-- for (i in clus) { -->
<!--     # KEGG ------------------------------------------------------------------------- -->
<!--     geneListEntrez = mapIds(org.Mm.eg.db, -->
<!--                             keys=rownames(i), -->
<!--                             column="ENTREZID", -->
<!--                             keytype="SYMBOL", -->
<!--                             multiVals="first") -->

<!--     Kres <- enrichKEGG(gene         = geneListEntrez, -->
<!--                        organism     = "mmu", -->
<!--                                   pAdjustMethod = "BH", -->
<!--                                   minGSSize    = 3, -->
<!--                                   pvalueCutoff  = 0.05, # slider -->
<!--                                   qvalueCutoff  = 0.05) -->

<!--     # Kresmat = as.matrix(Kres[]) -->

<!--     plot5 <- barplot(Kres, showCategory=15, order=T) + ggtitle(paste0("Barplot of functional enrichment by KEGG for cluster ")) -->
<!--     plot6 <- dotplot(Kres, showCategory=15) + ggtitle(paste0("Dotplot of functional enrichment by KEGG for cluster ")) -->

<!--     # GO --------------------------------------------------------------------------- -->
<!--     geneListEnsembl= mapIds(org.Mm.eg.db, -->
<!--                             keys=rownames(i), -->
<!--                             column="ENSEMBL", -->
<!--                             keytype="SYMBOL", -->
<!--                             multiVals="first") -->

<!--     enrichedRes_GO  <- enrichGO( -->
<!--       gene          = geneListEnsembl, -->
<!--       keyType       = "ENSEMBL", -->
<!--       OrgDb         = org.Mm.eg.db, -->
<!--       ont           = "BP", -->
<!--                                   pAdjustMethod = "BH", -->
<!--                                   minGSSize    = 3, -->
<!--                                   pvalueCutoff  = 0.05, # slider -->
<!--                                   qvalueCutoff  = 0.05, -->
<!--       readable      = TRUE) -->

<!--     # enrichedRes_GO_mat = as.matrix(enrichedRes_GO[]) -->

<!--     plot1 <- barplot(enrichedRes_GO, showCategory=15, order=T) + ggtitle(paste0("Barplot of functional enrichment by GO for cluster ")) -->
<!--     plot2 <- dotplot(enrichedRes_GO, showCategory=15) + ggtitle(paste0("Dotplot of functional enrichment by GO for cluster ")) -->

<!--     # REACTOM_PA-------------------------------------------------------------------- -->
<!--     geneListEntrez_PA = mapIds(org.Mm.eg.db, -->
<!--                                keys=rownames(i), -->
<!--                                column="ENTREZID", -->
<!--                                keytype="SYMBOL", -->
<!--                                multiVals="first") -->

<!--     enrichedRes_GS <- enrichPathway(gene = geneListEntrez_PA, -->
<!--                                     organism = 'mouse', -->
<!--                                   pAdjustMethod = "BH", -->
<!--                                   minGSSize    = 3, -->
<!--                                   pvalueCutoff  = 0.05, # slider -->
<!--                                   qvalueCutoff  = 0.05) -->

<!--     # enrichedRes_GS_mat = as.matrix(enrichedRes_GS[]) -->

<!--     plot3 <- barplot(enrichedRes_GS, showCategory=15, orderby="x") + ggtitle(paste0("Barplot of functional enrichment by REACTOM_PA for cluster")) -->
<!--     plot4 <- dotplot(enrichedRes_GS, showCategory=15) + ggtitle(paste0("Dotplot of functional enrichment by REACTOM_PA for cluster")) -->

<!--     # print(plot5) -->
<!--     print(plot6) -->
<!--     # print(plot1) -->
<!--     print(plot2) -->
<!--     # print(plot3) -->
<!--     print(plot4) -->
<!-- } -->

<!-- clus <- list(DE_0_vs_7) -->
<!-- nameclus <- c("DE_0_vs_7") -->
<!-- print(nameclus) -->

<!-- for (i in clus) { -->
<!--     # KEGG ------------------------------------------------------------------------- -->
<!--     geneListEntrez = mapIds(org.Mm.eg.db, -->
<!--                             keys=rownames(i), -->
<!--                             column="ENTREZID", -->
<!--                             keytype="SYMBOL", -->
<!--                             multiVals="first") -->

<!--     Kres <- enrichKEGG(gene         = geneListEntrez, -->
<!--                        organism     = "mmu", -->
<!--                                   pAdjustMethod = "BH", -->
<!--                                   minGSSize    = 3, -->
<!--                                   pvalueCutoff  = 0.05, # slider -->
<!--                                   qvalueCutoff  = 0.05) -->

<!--     # Kresmat = as.matrix(Kres[]) -->

<!--     plot5 <- barplot(Kres, showCategory=15, order=T) + ggtitle(paste0("Barplot of functional enrichment by KEGG for cluster ")) -->
<!--     plot6 <- dotplot(Kres, showCategory=15) + ggtitle(paste0("Dotplot of functional enrichment by KEGG for cluster ")) -->

<!--     # GO --------------------------------------------------------------------------- -->
<!--     geneListEnsembl= mapIds(org.Mm.eg.db, -->
<!--                             keys=rownames(i), -->
<!--                             column="ENSEMBL", -->
<!--                             keytype="SYMBOL", -->
<!--                             multiVals="first") -->

<!--     enrichedRes_GO  <- enrichGO( -->
<!--       gene          = geneListEnsembl, -->
<!--       keyType       = "ENSEMBL", -->
<!--       OrgDb         = org.Mm.eg.db, -->
<!--       ont           = "BP", -->
<!--                                   pAdjustMethod = "BH", -->
<!--                                   minGSSize    = 3, -->
<!--                                   pvalueCutoff  = 0.05, # slider -->
<!--                                   qvalueCutoff  = 0.05, -->
<!--       readable      = TRUE) -->

<!--     # enrichedRes_GO_mat = as.matrix(enrichedRes_GO[]) -->

<!--     plot1 <- barplot(enrichedRes_GO, showCategory=15, order=T) + ggtitle(paste0("Barplot of functional enrichment by GO for cluster ")) -->
<!--     plot2 <- dotplot(enrichedRes_GO, showCategory=15) + ggtitle(paste0("Dotplot of functional enrichment by GO for cluster ")) -->

<!--     # REACTOM_PA-------------------------------------------------------------------- -->
<!--     geneListEntrez_PA = mapIds(org.Mm.eg.db, -->
<!--                                keys=rownames(i), -->
<!--                                column="ENTREZID", -->
<!--                                keytype="SYMBOL", -->
<!--                                multiVals="first") -->

<!--     enrichedRes_GS <- enrichPathway(gene = geneListEntrez_PA, -->
<!--                                     organism = 'mouse', -->
<!--                                   pAdjustMethod = "BH", -->
<!--                                   minGSSize    = 3, -->
<!--                                   pvalueCutoff  = 0.05, # slider -->
<!--                                   qvalueCutoff  = 0.05) -->

<!--     # enrichedRes_GS_mat = as.matrix(enrichedRes_GS[]) -->

<!--     plot3 <- barplot(enrichedRes_GS, showCategory=15, orderby="x") + ggtitle(paste0("Barplot of functional enrichment by REACTOM_PA for cluster")) -->
<!--     plot4 <- dotplot(enrichedRes_GS, showCategory=15) + ggtitle(paste0("Dotplot of functional enrichment by REACTOM_PA for cluster")) -->

<!--     # print(plot5) -->
<!--     # print(plot6) -->
<!--     # print(plot1) -->
<!--     print(plot2) -->
<!--     # print(plot3) -->
<!--     print(plot4) -->
<!-- } -->
<!-- ``` -->

<!-- # 4 DE -->
<!-- ```{r, echo=FALSE, message=FALSE, warning=FALSE} -->
<!-- ### population ### -->
<!-- DE_LY49p_CD8aa_vs_ab <- FindMarkers(Singlet_norm, -->
<!--                                     group.by = "HTO_maxID", -->
<!--                                     ident.1 = "Ly49p-CD8aa", -->
<!--                                     ident.2 = "Ly49p-CD8ab", -->
<!--                                     only.pos = F, -->
<!--                                     min.pct = 0.1, #  diff de 0.1 entre les deux conditions -->
<!--                                     logfc.threshold = 0.5, -->
<!--                                     min.diff.pct = 0.25) -->
<!-- DE_VV_LY49p_CD8aa_vs_ab <- FindMarkers(Singlet_norm, -->
<!--                                     group.by = "HTO_maxID", -->
<!--                                     ident.1 = "VV-Ly49p-CD8aa", -->
<!--                                     ident.2 = "VV-Ly49p-CD8ab", -->
<!--                                     only.pos = F, -->
<!--                                     min.pct = 0.1, #  diff de 0.1 entre les deux conditions -->
<!--                                     logfc.threshold = 0.5, -->
<!--                                     min.diff.pct = 0.25) -->
<!-- DE_LY49p_CD8aa_vs_VV_aa <- FindMarkers(Singlet_norm, -->
<!--                                     group.by = "HTO_maxID", -->
<!--                                     ident.1 = "Ly49p-CD8aa", -->
<!--                                     ident.2 = "VV-Ly49p-CD8aa", -->
<!--                                     only.pos = F, -->
<!--                                     min.pct = 0.1, #  diff de 0.1 entre les deux conditions -->
<!--                                     logfc.threshold = 0.5, -->
<!--                                     min.diff.pct = 0.25) -->
<!-- DE_LY49p_CD8ab_vs_VV_ab <- FindMarkers(Singlet_norm, -->
<!--                                     group.by = "HTO_maxID", -->
<!--                                     ident.1 = "Ly49p-CD8ab", -->
<!--                                     ident.2 = "VV-Ly49p-CD8ab", -->
<!--                                     only.pos = F, -->
<!--                                     min.pct = 0.1, #  diff de 0.1 entre les deux conditions -->
<!--                                     logfc.threshold = 0.5, -->
<!--                                     min.diff.pct = 0.25) -->

<!-- ### cluster ### -->
<!-- DE_1_vs_2 <- FindMarkers(Singlet_norm, -->
<!--                                     group.by = "SCT_snn_res.0.5", -->
<!--                                     ident.1 = 1, -->
<!--                                     ident.2 = 2, -->
<!--                                     only.pos = F, -->
<!--                                     min.pct = 0.1, #  diff de 0.1 entre les deux conditions -->
<!--                                     logfc.threshold = 0.5, -->
<!--                                     min.diff.pct = 0.25) -->
<!-- DE_1_vs_4 <- FindMarkers(Singlet_norm, -->
<!--                                     group.by = "SCT_snn_res.0.5", -->
<!--                                     ident.1 = 1, -->
<!--                                     ident.2 = 4, -->
<!--                                     only.pos = F, -->
<!--                                     min.pct = 0.1, #  diff de 0.1 entre les deux conditions -->
<!--                                     logfc.threshold = 0.5, -->
<!--                                     min.diff.pct = 0.25) -->
<!-- DE_1_vs_2_4 <- FindMarkers(Singlet_norm, -->
<!--                                     group.by = "SCT_snn_res.0.5", -->
<!--                                     ident.1 = 1, -->
<!--                                     ident.2 = c(2,4), -->
<!--                                     only.pos = F, -->
<!--                                     min.pct = 0.1, #  diff de 0.1 entre les deux conditions -->
<!--                                     logfc.threshold = 0.5, -->
<!--                                     min.diff.pct = 0.25) -->
<!-- DE_0_vs_1 <- FindMarkers(Singlet_norm, -->
<!--                                     group.by = "SCT_snn_res.0.5", -->
<!--                                     ident.1 = 0, -->
<!--                                     ident.2 = 1, -->
<!--                                     only.pos = F, -->
<!--                                     min.pct = 0.1, #  diff de 0.1 entre les deux conditions -->
<!--                                     logfc.threshold = 0.5, -->
<!--                                     min.diff.pct = 0.25) -->
<!-- DE_0_vs_2 <- FindMarkers(Singlet_norm, -->
<!--                                     group.by = "SCT_snn_res.0.5", -->
<!--                                     ident.1 = 0, -->
<!--                                     ident.2 = 2, -->
<!--                                     only.pos = F, -->
<!--                                     min.pct = 0.1, #  diff de 0.1 entre les deux conditions -->
<!--                                     logfc.threshold = 0.5, -->
<!--                                     min.diff.pct = 0.25) -->
<!-- DE_0_vs_4 <- FindMarkers(Singlet_norm, -->
<!--                                     group.by = "SCT_snn_res.0.5", -->
<!--                                     ident.1 = 0, -->
<!--                                     ident.2 = 4, -->
<!--                                     only.pos = F, -->
<!--                                     min.pct = 0.1, #  diff de 0.1 entre les deux conditions -->
<!--                                     logfc.threshold = 0.5, -->
<!--                                     min.diff.pct = 0.25) -->
<!-- DE_0_vs_7 <- FindMarkers(Singlet_norm, -->
<!--                                     group.by = "SCT_snn_res.0.5", -->
<!--                                     ident.1 = 0, -->
<!--                                     ident.2 = 7, -->
<!--                                     only.pos = F, -->
<!--                                     min.pct = 0.1, #  diff de 0.1 entre les deux conditions -->
<!--                                     logfc.threshold = 0.5, -->
<!--                                     min.diff.pct = 0.25) -->
<!-- DE_0_vs_1_2_4_7 <- FindMarkers(Singlet_norm, -->
<!--                                     group.by = "SCT_snn_res.0.5", -->
<!--                                     ident.1 = 0, -->
<!--                                     ident.2 = c(1,2,4,7), -->
<!--                                     only.pos = F, -->
<!--                                     min.pct = 0.1, #  diff de 0.1 entre les deux conditions -->
<!--                                     logfc.threshold = 0.5, -->
<!--                                     min.diff.pct = 0.25) -->

<!-- DE_5_vs_8 <- FindMarkers(Singlet_norm, -->
<!--                                     group.by = "SCT_snn_res.0.5", -->
<!--                                     ident.1 = 5, -->
<!--                                     ident.2 = 8, -->
<!--                                     only.pos = F, -->
<!--                                     min.pct = 0.1, #  diff de 0.1 entre les deux conditions -->
<!--                                     logfc.threshold = 0.5, -->
<!--                                     min.diff.pct = 0.25) -->
<!-- #### Cluster 4 vrai ou faux cluster #### -->
<!-- DE_4_vs_1 <- FindMarkers(Singlet_norm, -->
<!--                                     group.by = "SCT_snn_res.0.5", -->
<!--                                     ident.1 = 4, -->
<!--                                     ident.2 = 1, -->
<!--                                     only.pos = F, -->
<!--                                     min.pct = 0.1, #  diff de 0.1 entre les deux conditions -->
<!--                                     logfc.threshold = 0.5, -->
<!--                                     min.diff.pct = 0.25) -->
<!-- DE_4_vs_2 <- FindMarkers(Singlet_norm, -->
<!--                                     group.by = "SCT_snn_res.0.5", -->
<!--                                     ident.1 = 4, -->
<!--                                     ident.2 = 2, -->
<!--                                     only.pos = F, -->
<!--                                     min.pct = 0.1, #  diff de 0.1 entre les deux conditions -->
<!--                                     logfc.threshold = 0.5, -->
<!--                                     min.diff.pct = 0.25) -->
<!-- DE_4_vs_1_2 <- FindMarkers(Singlet_norm, -->
<!--                                     group.by = "SCT_snn_res.0.5", -->
<!--                                     ident.1 = 4, -->
<!--                                     ident.2 = c(1,2), -->
<!--                                     only.pos = F, -->
<!--                                     min.pct = 0.1, #  diff de 0.1 entre les deux conditions -->
<!--                                     logfc.threshold = 0.5, -->
<!--                                     min.diff.pct = 0.25) -->
<!-- DE_4_vs_7 <- FindMarkers(Singlet_norm, -->
<!--                                     group.by = "SCT_snn_res.0.5", -->
<!--                                     ident.1 = 4, -->
<!--                                     ident.2 = 7, -->
<!--                                     only.pos = F, -->
<!--                                     min.pct = 0.1, #  diff de 0.1 entre les deux conditions -->
<!--                                     logfc.threshold = 0.5, -->
<!--                                     min.diff.pct = 0.25) -->
<!-- DE_4_vs_1_2_7 <- FindMarkers(Singlet_norm, -->
<!--                                     group.by = "SCT_snn_res.0.5", -->
<!--                                     ident.1 = 4, -->
<!--                                     ident.2 = c(1,2,7), -->
<!--                                     only.pos = F, -->
<!--                                     min.pct = 0.1, #  diff de 0.1 entre les deux conditions -->
<!--                                     logfc.threshold = 0.5, -->
<!--                                     min.diff.pct = 0.25) -->
<!-- ``` -->

<!-- Pas de DE entre le cluster 2 et 4 hypothèse d'une over clusterisation mais le DE entre le cluster 5 et 8 identifie 349 gènes -->
<!-- Peut être refaire avec une résolution de 0.4 et non 0.5 (cf Clustree) par rapport à la segmentation de la population LY49 infectée par VV -->
<!-- Question : Cluster 4 vrai ou faux cluster.... -->

<!-- ## 4.1 Visualization -->
<!-- ```{r, echo=FALSE, message=FALSE, warning=FALSE} -->
<!-- ### population ### -->
<!-- DoHeatmap(Singlet_norm, features = rownames(DE_LY49p_CD8aa_vs_ab), group.by = "HTO_maxID") + -->
<!--   NoLegend() + -->
<!--   ggtitle(label = "Heatmaps du DE LY49p_CD8aa_vs_ab") -->
<!-- DoHeatmap(Singlet_norm, features = rownames(DE_LY49p_CD8aa_vs_VV_aa), group.by = "HTO_maxID") + -->
<!--   NoLegend() + -->
<!--   ggtitle(label = "Heatmaps du DE LY49p_CD8aa_vs_VV_aa") -->
<!-- DoHeatmap(Singlet_norm, features = rownames(DE_LY49p_CD8ab_vs_VV_ab), group.by = "HTO_maxID") + -->
<!--   NoLegend() + -->
<!--   ggtitle(label = "Heatmaps du DE LY49p_CD8ab_vs_VV_ab") -->
<!-- DoHeatmap(Singlet_norm, features = rownames(DE_VV_LY49p_CD8aa_vs_ab), group.by = "HTO_maxID") + -->
<!--   NoLegend() + -->
<!--   ggtitle(label = "Heatmaps du DE VV_LY49p_CD8aa_vs_ab") -->

<!-- ### cluster ### -->
<!-- DoHeatmap(Singlet_norm, features = rownames(DE_1_vs_2), group.by = "SCT_snn_res.0.5") + -->
<!--   NoLegend() + -->
<!--   ggtitle(label = "Heatmaps du DE 1_vs_2") -->
<!-- DoHeatmap(Singlet_norm, features = rownames(DE_1_vs_4), group.by = "SCT_snn_res.0.5") + -->
<!--   NoLegend() + -->
<!--   ggtitle(label = "Heatmaps du DE 1_vs_4") -->
<!-- DoHeatmap(Singlet_norm, features = rownames(DE_1_vs_2_4), group.by = "SCT_snn_res.0.5") + -->
<!--   NoLegend() + -->
<!--   ggtitle(label = "Heatmaps du DE 1_vs_2_4") -->
<!-- DoHeatmap(Singlet_norm, features = rownames(DE_0_vs_1), group.by = "SCT_snn_res.0.5") + -->
<!--   NoLegend() + -->
<!--   ggtitle(label = "Heatmaps du DE 0_vs_1") -->
<!-- DoHeatmap(Singlet_norm, features = rownames(DE_0_vs_2), group.by = "SCT_snn_res.0.5") + -->
<!--   NoLegend() + -->
<!--   ggtitle(label = "Heatmaps du DE 0_vs_2") -->
<!-- DoHeatmap(Singlet_norm, features = rownames(DE_0_vs_4), group.by = "SCT_snn_res.0.5") + -->
<!--   NoLegend() + -->
<!--   ggtitle(label = "Heatmaps du DE 0_vs_4") -->
<!-- DoHeatmap(Singlet_norm, features = rownames(DE_0_vs_7), group.by = "SCT_snn_res.0.5") + -->
<!--   NoLegend() + -->
<!--   ggtitle(label = "Heatmaps du DE 0_vs_7") -->
<!-- DoHeatmap(Singlet_norm, features = rownames(DE_0_vs_1_2_4_7), group.by = "SCT_snn_res.0.5") + -->
<!--   NoLegend() + -->
<!--   ggtitle(label = "Heatmaps du DE 0_vs_1_2_4_7") -->
<!-- ``` -->


